export const SELECT_PHOTO = 'SELECT_PHOTO'

export const POOL_LOAD = 'POOL_LOAD'
export const POOL_SHUFFLE = 'POOL_SHUFFLE'

export const TREE_TOGGLE_VISIBILITY = 'TREE_TOGGLE_VISIBILITY'
export const TREE_OPEN_DIRECTORY = 'TREE_OPEN_DIRECTORY'